export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_AVATARS = 'GET_AVATARS';
export const CHOOSE_AVATAR = 'CHOOSE_AVATAR';
export const ADD_CHOSEN_AVATAR = 'ADD_CHOSEN_AVATAR';
export const REMOVE_CHOSEN_AVATAR = 'REMOVE_CHOSEN_AVATAR';
export const REORDER_AVATARS = 'REORDER_AVATARS';
